# Generated by Django 5.2.10 on 2026-02-18 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='articles', to='blogs.tag'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title', 'created_time', 'updated_time'], name='normal'),
        ),
    ]
